changelog:
  exclude:
    labels:
      - ignored
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - breaking
    - title: ✨ New Features / Improvements
      labels:
        - feature
        - improvement
    - title: 🪳 Bug Fixes
      labels:
        - bugfix
    - title: 📦 Dependency Updates
      labels:
        - dependency
    - title: 📝 Documentation
      labels:
        - documentation
    - title: 🧪 Testing
      labels:
        - testing
    - title: 🧹 Tech debt
      labels:
        - tech-debt
        - chore
    - title: Other Changes
      labels:
        - misc
